// Regenerates src/lib/api/schema.d.ts (typed client) and docs/openapi.json + docs/api-endpoints.md from the running backend.
//   pnpm gen:api                      → http://localhost:8080/api/openapi.json
//   pnpm gen:api --url <url|file>     → another backend / a saved openapi.json
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const arg = process.argv.indexOf('--url');
const source = arg > -1 ? process.argv[arg + 1] : 'http://localhost:8080/api/openapi.json';

async function load() {
	if (/^https?:/.test(source)) {
		const response = await fetch(source);
		if (!response.ok) throw new Error(`${source} → HTTP ${response.status}`);
		return response.json();
	}
	return JSON.parse(await readFile(resolve(source), 'utf8'));
}

const spec = await load();
await mkdir(resolve(root, 'docs'), { recursive: true });
await writeFile(resolve(root, 'docs/openapi.json'), JSON.stringify(spec, null, 2));

const ast = await openapiTS(spec, { exportType: true });
await writeFile(resolve(root, 'src/lib/api/schema.d.ts'), `// GENERATED by tools/gen-api.mjs from the backend OpenAPI — do not edit.\n${astToString(ast)}`);

// human-readable endpoint index for agents/reviewers
const rows = [];
for (const [path, item] of Object.entries(spec.paths ?? {})) {
	for (const method of ['get', 'post', 'put', 'patch', 'delete']) {
		const op = item[method];
		if (op) rows.push({ tag: (op.tags ?? ['—'])[0], method: method.toUpperCase(), path, summary: op.summary ?? '' });
	}
}
rows.sort((a, b) => a.tag.localeCompare(b.tag) || a.path.localeCompare(b.path));
let md = `# Эндпоинты бэкенда (${rows.length})\n\n_Сгенерировано tools/gen-api.mjs._\n`;
let tag = '';
for (const r of rows) {
	if (r.tag !== tag) {
		tag = r.tag;
		md += `\n## ${tag}\n\n| Метод | Путь | Описание |\n|---|---|---|\n`;
	}
	md += `| ${r.method} | \`${r.path}\` | ${r.summary} |\n`;
}
await writeFile(resolve(root, 'docs/api-endpoints.md'), md);
console.log(`schema.d.ts written · ${rows.length} operations · docs/openapi.json, docs/api-endpoints.md`);
